name: qrx_app
description: A Flutter app for verifying medicine authenticity via QR scanning.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: 5.1.1
  flutter_tts: ^3.8.5
  http: ^1.6.0 # Added HTTP package for network requests
  provider: ^6.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
